apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neo4jchart.fullname" . }}
  labels:
    {{- include "neo4jchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "neo4jchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "neo4jchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "neo4jchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # ...
          ports:
            - name: http
              containerPort: {{ (index .Values.service.ports 0).targetPort }}
              protocol: TCP
            - name: bolt
              containerPort: {{ (index .Values.service.ports 1).targetPort }}
              protocol: TCP
          # probes
          livenessProbe:
            tcpSocket:
              port: bolt
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: bolt
            initialDelaySeconds: 30
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # volumes
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            # - name: neo4j-config
            #   mountPath: /conf
            #   subPath: neo4j.conf
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: {{ include "neo4jchart.fullname" . }}-pvc
        # - name: neo4j-config
        #   configMap:
        #     name: {{ .Values.configMap.name }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
