apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "neo4jchart.fullname" . }}-pvc
  labels:
    {{- include "neo4jchart.labels" . | nindent 4 }}
    {{- with .Values.pvc.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.pvc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- if .Values.pvc.matchLabels }}
  selector:
    matchLabels:
      {{- toYaml .Values.pvc.matchLabels | nindent 6 }}
  {{- end }}
  {{- with .Values.pvc.dataSource }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
