apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4jchart.fullname" . }}
  labels:
    {{- include "neo4jchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ (index .Values.service.ports 0).port }}
      targetPort: {{ (index .Values.service.ports 0).targetPort }}
      protocol: TCP
    - name: bolt
      port: {{ (index .Values.service.ports 1).port }}
      targetPort: {{ (index .Values.service.ports 1).targetPort }}
      protocol: TCP

  selector:
    {{- include "neo4jchart.selectorLabels" . | nindent 4 }}
