# database system for metrics
---
global:
  scrape_interval: 5s
  scrape_timeout: 3s
server:
  resources:
    requests:
      memory: "200Mi"
      cpu: "300m"
    limits:
      memory: "1Gi"
      cpu: "1"

  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
  readinessProbeInitialDelay: 0
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 655
  persistentVolume:
    enabled: true
    size: 10Gi
alertmanager:
  enabled: false
nodeExporter:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
pushgateway:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
kube-state-metrics:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
serviceAccounts:
  alertmanager:
    create: true
    name:
    annotations: {}
  nodeExporter:
    create: true
    name:
    annotations: {}
  pushgateway:
    create: true
    name:
    annotations: {}
  server:
    create: true
    name:
    annotations: {}
