replicaCount: 2

image:
  repository: wsbohm/cookify-photo-service-test
  pullPolicy: IfNotPresent
  tag: "1.0.1"

podAnnotations:
  consul.hashicorp.com/connect-inject: "true"

service:
  type: ClusterIP
  port: 8066

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: your-app.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "production"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
