apiVersion: v1
kind: ConfigMap
metadata:
  name: Cookify-port-config-map
data:
  JWTSERVICE_PORT: "8081"
  PHOTOSERVICE_PORT: "8082"
  RECIPESERVICE_PORT: "8083"
  RECOMENDATIONSERVICE_PORT: "8084"
  USERSERVICE_PORT: "8085"
  VIDEOSTREAMSERVICE_PORT: "8086"
  MONGODB_PORT: "8087"
  NEO4J_PORT: "8088"
  ELASTICSEARCH_PORT: "8089"
  LOGSTASH_PORT: "8090"
  KIBANA_PORT: "8091"
  ELK_LOG_AGGREGATE_PORT: "8092"
  RABBITMQ_PORT: "8093"
  VAULT_PORT: "8094"
